version: '3.5'

services:
  aspnet-api:
    image: aspnet-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "User ID=api_user;Password=password12;Host=postgres_image;Port=5432;Database=userdb;Integrated Security=true;Pooling=true"
    networks:
      - default-network
  
  postgres_image:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-api_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password12}
      POSTGRES_DB: ${POSTGRES_DB:-userdb}
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default-network
    restart: unless-stopped



networks:
  default-network:
    driver: bridge 

volumes:
  postgres:
  pgadmin: